spring:
  application:
    name: StockServer
  datasource:
    url: jdbc:sqlite:stock_server.sqllite
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 100
stock-server:
  tiingo:
    url: https://api.tiingo.com/tiingo
  alpha_vantage:
    url: https://www.alphavantage.co
